// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using fit.Data;

#nullable disable

namespace fit.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("fit.Models.Badge", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("EarnedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Icon")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Badges");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Completed your first workout",
                            EarnedAt = new DateTime(2025, 5, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Icon = "🏋️",
                            Name = "First Workout",
                            UserId = 3
                        },
                        new
                        {
                            Id = 2,
                            Description = "Worked out 3 days in a row",
                            EarnedAt = new DateTime(2025, 5, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Icon = "🔥",
                            Name = "3-Day Streak",
                            UserId = 3
                        });
                });

            modelBuilder.Entity("fit.Models.BodyWeight", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<string>("Note")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<float>("Weight")
                        .HasColumnType("real");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("BodyWeights");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Date = new DateTime(2025, 5, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Note = "Starting weight",
                            UserId = 3,
                            Weight = 72.5f
                        },
                        new
                        {
                            Id = 2,
                            Date = new DateTime(2025, 5, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UserId = 3,
                            Weight = 71.8f
                        },
                        new
                        {
                            Id = 3,
                            Date = new DateTime(2025, 5, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UserId = 3,
                            Weight = 71.2f
                        },
                        new
                        {
                            Id = 4,
                            Date = new DateTime(2025, 5, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UserId = 3,
                            Weight = 70.5f
                        },
                        new
                        {
                            Id = 5,
                            Date = new DateTime(2025, 5, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UserId = 4,
                            Weight = 85f
                        },
                        new
                        {
                            Id = 6,
                            Date = new DateTime(2025, 5, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UserId = 4,
                            Weight = 84.2f
                        });
                });

            modelBuilder.Entity("fit.Models.Food", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<float>("CaloriesPer100g")
                        .HasColumnType("real");

                    b.Property<float>("CarbsPer100g")
                        .HasColumnType("real");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<float>("FatPer100g")
                        .HasColumnType("real");

                    b.Property<bool>("IsLocal")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<float>("ProteinPer100g")
                        .HasColumnType("real");

                    b.HasKey("Id");

                    b.ToTable("Foods");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CaloriesPer100g = 360f,
                            CarbsPer100g = 79f,
                            Category = "Grains",
                            FatPer100g = 1f,
                            IsLocal = true,
                            Name = "Ugali",
                            ProteinPer100g = 3f
                        },
                        new
                        {
                            Id = 2,
                            CaloriesPer100g = 45f,
                            CarbsPer100g = 6f,
                            Category = "Vegetables",
                            FatPer100g = 1f,
                            IsLocal = true,
                            Name = "Isombe (Cassava Leaves)",
                            ProteinPer100g = 4f
                        },
                        new
                        {
                            Id = 3,
                            CaloriesPer100g = 77f,
                            CarbsPer100g = 17f,
                            Category = "Vegetables",
                            FatPer100g = 0.1f,
                            IsLocal = true,
                            Name = "Ibirayi (Potatoes)",
                            ProteinPer100g = 2f
                        },
                        new
                        {
                            Id = 4,
                            CaloriesPer100g = 347f,
                            CarbsPer100g = 63f,
                            Category = "Legumes",
                            FatPer100g = 1f,
                            IsLocal = true,
                            Name = "Beans (Ibishyimbo)",
                            ProteinPer100g = 22f
                        },
                        new
                        {
                            Id = 5,
                            CaloriesPer100g = 165f,
                            CarbsPer100g = 0f,
                            Category = "Protein",
                            FatPer100g = 3.6f,
                            IsLocal = false,
                            Name = "Chicken Breast",
                            ProteinPer100g = 31f
                        },
                        new
                        {
                            Id = 6,
                            CaloriesPer100g = 89f,
                            CarbsPer100g = 23f,
                            Category = "Fruits",
                            FatPer100g = 0.3f,
                            IsLocal = true,
                            Name = "Banana (Igitoki)",
                            ProteinPer100g = 1.1f
                        },
                        new
                        {
                            Id = 7,
                            CaloriesPer100g = 61f,
                            CarbsPer100g = 4.8f,
                            Category = "Dairy",
                            FatPer100g = 3.3f,
                            IsLocal = true,
                            Name = "Milk (Amata)",
                            ProteinPer100g = 3.2f
                        },
                        new
                        {
                            Id = 8,
                            CaloriesPer100g = 86f,
                            CarbsPer100g = 20f,
                            Category = "Vegetables",
                            FatPer100g = 0.1f,
                            IsLocal = true,
                            Name = "Sweet Potato (Ibijumba)",
                            ProteinPer100g = 1.6f
                        });
                });

            modelBuilder.Entity("fit.Models.Goal", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<float>("CurrentValue")
                        .HasColumnType("real");

                    b.Property<DateTime>("Deadline")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsCompleted")
                        .HasColumnType("bit");

                    b.Property<string>("PreferredTrainerGender")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<float>("TargetValue")
                        .HasColumnType("real");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Goals");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CurrentValue = 70.5f,
                            Deadline = new DateTime(2025, 8, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsCompleted = false,
                            PreferredTrainerGender = "Any",
                            TargetValue = 67.5f,
                            Title = "Lose 5kg",
                            Type = "Weight",
                            UserId = 3
                        },
                        new
                        {
                            Id = 2,
                            CurrentValue = 3f,
                            Deadline = new DateTime(2025, 7, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsCompleted = false,
                            PreferredTrainerGender = "Any",
                            TargetValue = 5f,
                            Title = "Run 5km daily",
                            Type = "Workout",
                            UserId = 3
                        },
                        new
                        {
                            Id = 3,
                            CurrentValue = 84.2f,
                            Deadline = new DateTime(2025, 9, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsCompleted = false,
                            PreferredTrainerGender = "Any",
                            TargetValue = 90f,
                            Title = "Build muscle mass",
                            Type = "Weight",
                            UserId = 4
                        });
                });

            modelBuilder.Entity("fit.Models.Location", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Province")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Sector")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("Province", "Sector")
                        .IsUnique();

                    b.ToTable("Locations");
                });

            modelBuilder.Entity("fit.Models.MoodLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<int>("EnergyScore")
                        .HasColumnType("int");

                    b.Property<int>("MoodScore")
                        .HasColumnType("int");

                    b.Property<string>("Note")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("MoodLogs");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Date = new DateTime(2025, 5, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EnergyScore = 5,
                            MoodScore = 4,
                            Note = "Feeling motivated!",
                            UserId = 3
                        },
                        new
                        {
                            Id = 2,
                            Date = new DateTime(2025, 5, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EnergyScore = 3,
                            MoodScore = 3,
                            UserId = 3
                        });
                });

            modelBuilder.Entity("fit.Models.Notification", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsRead")
                        .HasColumnType("bit");

                    b.Property<string>("Link")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RecipientRole")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("RecipientUserId")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("RecipientUserId", "IsRead", "CreatedAt");

                    b.ToTable("Notifications");
                });

            modelBuilder.Entity("fit.Models.NutritionLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<int>("FoodId")
                        .HasColumnType("int");

                    b.Property<float>("Grams")
                        .HasColumnType("real");

                    b.Property<string>("MealType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("FoodId");

                    b.HasIndex("UserId");

                    b.ToTable("NutritionLogs");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Date = new DateTime(2025, 5, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FoodId = 4,
                            Grams = 200f,
                            MealType = "Lunch",
                            UserId = 3
                        },
                        new
                        {
                            Id = 2,
                            Date = new DateTime(2025, 5, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FoodId = 6,
                            Grams = 150f,
                            MealType = "Breakfast",
                            UserId = 3
                        },
                        new
                        {
                            Id = 3,
                            Date = new DateTime(2025, 5, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FoodId = 5,
                            Grams = 150f,
                            MealType = "Dinner",
                            UserId = 3
                        });
                });

            modelBuilder.Entity("fit.Models.Role", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Roles");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Admin"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Trainer"
                        },
                        new
                        {
                            Id = 3,
                            Name = "User"
                        });
                });

            modelBuilder.Entity("fit.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Gender")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("LocationId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.Property<int?>("TrainerId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("LocationId");

                    b.HasIndex("RoleId");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "admin@fittrack.rw",
                            Gender = "Male",
                            Name = "Admin User",
                            PasswordHash = "$2a$11$q1WSoNCn3OW9yZH1mlnhWO0aS7PoNqpuv.BYZtQX789/AMsv2nCsy",
                            RoleId = 1
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "trainer@fittrack.rw",
                            Gender = "Male",
                            Name = "Jean Trainer",
                            PasswordHash = "$2a$11$LD90HXmSKZHpvrQbFcNjU.B.bXbYsRT8qS2EZyAyxB7WSoYzLDZuu",
                            RoleId = 2
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "alice@fittrack.rw",
                            Gender = "Female",
                            Name = "Alice Uwase",
                            PasswordHash = "$2a$11$n1Xo51XXkQy2ABL65mkyWeKwTtG1kFX4urXvANI/.1JA8SgTW9PLm",
                            RoleId = 3,
                            TrainerId = 2
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "bob@fittrack.rw",
                            Gender = "Male",
                            Name = "Bob Mugisha",
                            PasswordHash = "$2a$11$MyhOo8KzwMizE9U6HzYmbeQlPW0az0tgoVQwxHwx/qKMQZeCW/Cf2",
                            RoleId = 3,
                            TrainerId = 2
                        });
                });

            modelBuilder.Entity("fit.Models.WorkoutLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CaloriesBurned")
                        .HasColumnType("int");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<int>("DurationMinutes")
                        .HasColumnType("int");

                    b.Property<string>("Notes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<int>("WorkoutPlanId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.HasIndex("WorkoutPlanId");

                    b.ToTable("WorkoutLogs");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CaloriesBurned = 280,
                            Date = new DateTime(2025, 5, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DurationMinutes = 35,
                            Notes = "Felt great!",
                            UserId = 3,
                            WorkoutPlanId = 1
                        },
                        new
                        {
                            Id = 2,
                            CaloriesBurned = 250,
                            Date = new DateTime(2025, 5, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DurationMinutes = 30,
                            UserId = 3,
                            WorkoutPlanId = 1
                        },
                        new
                        {
                            Id = 3,
                            CaloriesBurned = 320,
                            Date = new DateTime(2025, 5, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DurationMinutes = 45,
                            UserId = 3,
                            WorkoutPlanId = 2
                        },
                        new
                        {
                            Id = 4,
                            CaloriesBurned = 400,
                            Date = new DateTime(2025, 5, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DurationMinutes = 60,
                            UserId = 4,
                            WorkoutPlanId = 2
                        });
                });

            modelBuilder.Entity("fit.Models.WorkoutPlan", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CreatedByUserId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Difficulty")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("WorkoutPlans");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedByUserId = 2,
                            Description = "30-min morning run and stretching",
                            Difficulty = "Beginner",
                            Name = "Morning Cardio"
                        },
                        new
                        {
                            Id = 2,
                            CreatedByUserId = 2,
                            Description = "Full body strength training",
                            Difficulty = "Intermediate",
                            Name = "Strength Builder"
                        },
                        new
                        {
                            Id = 3,
                            CreatedByUserId = 2,
                            Description = "High intensity interval training",
                            Difficulty = "Advanced",
                            Name = "HIIT Blast"
                        });
                });

            modelBuilder.Entity("fit.Models.Badge", b =>
                {
                    b.HasOne("fit.Models.User", "User")
                        .WithMany("Badges")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("fit.Models.BodyWeight", b =>
                {
                    b.HasOne("fit.Models.User", "User")
                        .WithMany("BodyWeights")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("fit.Models.Goal", b =>
                {
                    b.HasOne("fit.Models.User", "User")
                        .WithMany("Goals")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("fit.Models.MoodLog", b =>
                {
                    b.HasOne("fit.Models.User", "User")
                        .WithMany("MoodLogs")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("fit.Models.Notification", b =>
                {
                    b.HasOne("fit.Models.User", "RecipientUser")
                        .WithMany("Notifications")
                        .HasForeignKey("RecipientUserId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("RecipientUser");
                });

            modelBuilder.Entity("fit.Models.NutritionLog", b =>
                {
                    b.HasOne("fit.Models.Food", "Food")
                        .WithMany()
                        .HasForeignKey("FoodId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("fit.Models.User", "User")
                        .WithMany("NutritionLogs")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Food");

                    b.Navigation("User");
                });

            modelBuilder.Entity("fit.Models.User", b =>
                {
                    b.HasOne("fit.Models.Location", "Location")
                        .WithMany("Users")
                        .HasForeignKey("LocationId");

                    b.HasOne("fit.Models.Role", "Role")
                        .WithMany("Users")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Location");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("fit.Models.WorkoutLog", b =>
                {
                    b.HasOne("fit.Models.User", "User")
                        .WithMany("WorkoutLogs")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("fit.Models.WorkoutPlan", "WorkoutPlan")
                        .WithMany("Logs")
                        .HasForeignKey("WorkoutPlanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");

                    b.Navigation("WorkoutPlan");
                });

            modelBuilder.Entity("fit.Models.Location", b =>
                {
                    b.Navigation("Users");
                });

            modelBuilder.Entity("fit.Models.Role", b =>
                {
                    b.Navigation("Users");
                });

            modelBuilder.Entity("fit.Models.User", b =>
                {
                    b.Navigation("Badges");

                    b.Navigation("BodyWeights");

                    b.Navigation("Goals");

                    b.Navigation("MoodLogs");

                    b.Navigation("Notifications");

                    b.Navigation("NutritionLogs");

                    b.Navigation("WorkoutLogs");
                });

            modelBuilder.Entity("fit.Models.WorkoutPlan", b =>
                {
                    b.Navigation("Logs");
                });
#pragma warning restore 612, 618
        }
    }
}
